server:
  port: 8665

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8666/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
  application:
    name: yato

